### ISSUE TITLE
Way to make it bigger?

### ISSUE THREAD

**Issue by MeowCatYT** [avenom/Spotibar#1]
Is there a way to make anything bigger? For example the cover art and other stuff? I wanted it to make it like a mini player and for me it's way much smaller. is there a way to make it bigger?

**Comment by avenom** [comment]
> Is there a way to make anything bigger? For example the cover art and other stuff? I wanted it to make it like a mini player and for me it's way much smaller. is there a way to make it bigger?

Unfortunately everything is specified in pixels, I could probably do it in percentages, but would need to check in different resolutions.

You can manually change the dimensions in this section:

[Variables].
Font=Roboto
TextAlign=Right
**TextX=184
TextW=180
TextH=20**
Color=FFFFFFFF
Highlight=1DB954
Volume=3
**ButtonWH=20
ButtonWHplay=25
ButtonWHsr=18**
Rating=5
**Scale=1.00
CoverSize=35**
CoverRadius=0
ProgressBarThickness=2

And look for any "Size" in other lines.
