### ISSUE TITLE
Pinning the window

### ISSUE THREAD

**Issue by Axxilotl** [avenom/Spotibar#2]
There doesn't seem to be a way to pin the window on top of other windows? The other tabs on rainmeter seem to have this option but Spotibar does not. :(

**Comment by TheInternetUse7** [comment]
I would love to have this addition. I was hoping to be able to pin it on the bottom right corner just above the time and stuff.
Optionally, if it could be invisible and fade in only when we hover the mouse over it.

**Comment by avenom** [comment]
> There doesn't seem to be a way to pin the window on top of other windows? The other tabs on rainmeter seem to have this option but Spotibar does not. :(

I don't see what the problem is. I have "Stay topmost" option in Rainmeter. Send me screenshot.

**Comment by avenom** [comment]
> I would love to have this addition. I was hoping to be able to pin it on the bottom right corner just above the time and stuff. Optionally, if it could be invisible and fade in only when we hover the mouse over it.

I'm not sure what you need. You can move it anywhere or you want mini-player to appear only on mouseover?

**Comment by TheInternetUse7** [comment]
> I have "Stay topmost" option in Rainmeter.

Never mind. It was a simple option I failed to change. What I wanted already exists. As a new user I didn't know about this. Thanks.

![Spotibar setting in Rainmeter](https://theinternetuser.is-from.space/r/Rainmeter_v86jeBjnNt.png)
